[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"
  environment = { NODE_VERSION = "24" }

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.22"
  TZ = "UTC"

[context.production.environment]
  HUGO_VERSION = "0.150.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.150.1"